### ISSUE TITLE
Problem running maven-plugin on Windows:Unexpected internal error near index 1 \. Caused by File.separatorChar and Regex

### ISSUE THREAD

**Issue by eKutchy** [adrobisch/raml-converter#1]
I've some problem running the maven-plugin on a Windows 7, it seams the problem is in RamlHTmlMojo.java at line 65 on getting the output file name. You're using fileName.split(""+File.separatorChar). File.separatorChar is Windows is \, escaped as String like "\" that it is not a valid Regex. The right regular expression might be \ that escaped would be "\\".

**Comment by adrobisch** [comment]
Yes,  makes sense to me, I will prepare a fix. Thanks for reporting!
