### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by david-mas** [adrobisch/raml-converter#16]
Please make a release 0.14 since the separatorChar makes the plugin fail in windows. In windows File.pathSeparator is '\' but the file is in URI format, therefore the last part is never found.

Tested 0.14-SNAPSHOT built on local and the separator works fine in windows.

**Comment by adrobisch** [comment]
Hi, thanks for the request! I will push a new version by tomorrow.

**Comment by david-mas** [comment]
I can help to get the release if you need it.

**Comment by adrobisch** [comment]
Sorry for the delay, version 0.14 is now in central.
