### ISSUE TITLE
Problem parsing a .raml file containing !include: resource not found.

### ISSUE THREAD

**Issue by eKutchy** [adrobisch/raml-converter#2]
Running the maven-plugin on a raml file containing !include tag, the parsing fails, due to a "resource not found" error. In my raml file I tried to include types from a "common-types.raml" file, but it seems raml-parser cannot load the resource, I've also tried to specify the absolute path or the classpath ("classpath:common-types.raml") but still not working. Any idea of the problem?

**Comment by adrobisch** [comment]
Thanks for reporting this issue. I will try to reproduce this behaviour and look into it.

**Comment by adrobisch** [comment]
I created a new release (0.5) in the bintray repo, where this issue (and also #1)is fixed. Don't hesitate to create new issues if you find some. Cheers!
