### ISSUE TITLE
Attributes of URI parameters are not fully supported

### ISSUE THREAD

**Issue by gino0631** [adrobisch/raml-converter#3]
According to the RAML specification the value of an `uriParameters` property is "a map that specifies the property's attributes, according to the Named Parameters section", as well as the value of a `queryParameters` property. However, these properties are handled differently - `queryParam.hbs` has support for many attributes while URI parameters are handled in `action-body.hbs` directly with only a minimal support (e.g. no enum values, no descriptions).
I'd suggest to reuse the same template for all "Named Parameters" if that's possible.

**Comment by adrobisch** [comment]
Hi Gino,
your are right, parameter are not consistent currently. I will fix this.

Regards,
Andreas

**Comment by adrobisch** [comment]
created release 0.11 for that, should be in central soon

**Comment by gino0631** [comment]
Cool, thanks!
