### ISSUE TITLE
Inconsistency in Headers property handling

### ISSUE THREAD

**Issue by gino0631** [adrobisch/raml-converter#4]
Another inconsistency I have noticed so far - `headers` property in requests and responses looks differently, for example:
Request:
**Authorization**: (string) The authentication...
Response:
Date (STRING) The time...

Since, according to the RAML specification, the value of the `headers` property is "a map specifying the header attributes, according to the Named Parameters section", I'd suggest reusing the same template as for other "Named Parameters".

**Comment by adrobisch** [comment]
Hi Gino,
thanks for reporting this, I will look into it asap.

Regards,
Andreas

**Comment by gino0631** [comment]
Thank you, this is not urgent.

**Comment by gino0631** [comment]
BTW it looks like Markdown is not supported in the `description` attribute of the `headers` property, but this should get fixed by reusing the "Named Parameters" template as well.
